# ----------------- Possible Values ----------------- #
# difficulty: PEACEFUL, EASY, NORMAL, HARD            #
# gamemode: SURVIVAL, CREATIVE, ADVENTURE, SPECTATOR  #
# --------------------------------------------------- #

worlds: {}
