name: WorldLoad
author: piluke, originally by Agazed
description: Load or generate a world
website: https://github.com/piluke/WorldLoad
main: net.agazed.worldload.WorldLoad
version: 4.4
api-version: 1.13
commands:
  worldload:
    description: Main command for WorldLoad
    aliases: [wl]
permissions:
    worldload.help:
        description: Displays help page
        default: op
    worldload.info:
        description: Displays world info
        default: op
    worldload.tp:
        description: Teleport to a world
        default: op
    worldload.create:
        description: Create a world
        default: op
    worldload.remove:
        description: Remove a world from the config
        default: op
    worldload.load:
        description: Load a world one time
        default: op
    worldload.unload:
        description: Unload a world one time
        default: op
    worldload.list:
        description: List your worlds
        default: op
    worldlist.reload:
        description: Reload the config
        default: op
    worldlist.home:
        description: Set and tp to homes
        default: op
